x-logging: &default-logging
  driver: "json-file"
  options:
    max-size: "10m"
    max-file: "3"
    compress: "true"

x-healthcheck: &default-healthcheck
  interval: 10s
  timeout: 5s
  retries: 5
  start_period: 30s

services:

  ###############################
  ### APPLICATION SERVICES     ###
  ###############################
  techwikiplus:
    build:
      context: .
      dockerfile: Dockerfile
    image: techwikiplus/server:latest
    container_name: techwikiplus
    restart: on-failure:3
    environment:
      # Database Configuration
      SPRING_MYSQL_HOST: ${SPRING_MYSQL_HOST}
      SPRING_MYSQL_PORT: ${SPRING_MYSQL_PORT}
      SPRING_MYSQL_DATABASE: ${SPRING_MYSQL_DATABASE}
      SPRING_MYSQL_USER: ${SPRING_MYSQL_USER}
      SPRING_MYSQL_PASSWORD: ${SPRING_MYSQL_PASSWORD}
      
      # Redis Configuration
      SPRING_REDIS_HOST: ${SPRING_REDIS_HOST}
      SPRING_REDIS_PORT: ${SPRING_REDIS_PORT}
      SPRING_REDIS_PASSWORD: ${SPRING_REDIS_PASSWORD}
      
      # Mail Configuration
      SPRING_MAIL_HOST: ${SPRING_MAIL_HOST}
      SPRING_MAIL_PORT: ${SPRING_MAIL_PORT}
      SPRING_MAIL_USERNAME: ${SPRING_MAIL_USERNAME}
      SPRING_MAIL_PASSWORD: ${SPRING_MAIL_PASSWORD}
      SPRING_MAIL_SMTP_AUTH: ${SPRING_MAIL_SMTP_AUTH}
      SPRING_MAIL_SMTP_STARTTLS: ${SPRING_MAIL_SMTP_STARTTLS}
      
      # Security Configuration
      SPRING_JWT_SECRET: ${SPRING_JWT_SECRET}
      
      # Management Security Configuration
      MANAGEMENT_ENDPOINTS_WEB_EXPOSURE_INCLUDE: health,metrics,prometheus
      MANAGEMENT_SECURITY_ENABLED: false
    ports:
      - "9000:9000"  # 애플리케이션 메인 포트 (Actuator 포함)
    volumes:
      - app-logs:/app/logs
    depends_on:
      mysql:
        condition: service_healthy
      redis:
        condition: service_healthy
      mailhog:
        condition: service_healthy
    networks:
      - backend
    logging: *default-logging
    healthcheck:
      <<: *default-healthcheck
      test: ["CMD", "curl", "-f", "http://localhost:9000/actuator/health"]
      start_period: 120s
      interval: 30s
    deploy:
      resources:
        limits:
          memory: 1024M
          cpus: '1.0'
        reservations:
          memory: 512M
          cpus: '0.5'

networks:
  web:
  backend:
    driver: bridge

volumes:
  app-logs:
    driver: local
