services:
  # 빠른 프로덕션 빌드
  frontend:
    build:
      context: .
      dockerfile: Dockerfile.optimized
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - NEXT_TELEMETRY_DISABLED=1
      - HOSTNAME=0.0.0.0
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost:3000"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # 빠른 개발 환경
  frontend-dev:
    build:
      context: .
      dockerfile: Dockerfile.dev.optimized
      args:
        BUILDKIT_INLINE_CACHE: 1
    ports:
      - "3000:3000"
    volumes:
      - ./apps/frontend:/app
      - /app/node_modules
      - /app/.next
    environment:
      - NODE_ENV=development
      - WATCHPACK_POLLING=true
    profiles:
      - development
    stdin_open: true
    tty: true