package me.helloc.techwikiplus.post.domain.exception

enum class PostErrorCode {
    // Post Status
    POST_NOT_FOUND,
    POST_DELETED,
    POST_DRAFT,
    POST_IN_REVIEW,

    // Post Management
    DUPLICATE_TITLE,
    INVALID_POST_STATE,
    FORBIDDEN_POST_ROLE,

    // Title Validation
    BLANK_TITLE,
    TITLE_TOO_LONG,
    TITLE_CONTAINS_INVALID_CHAR,

    // Content Validation
    BLANK_CONTENT,
    CONTENT_TOO_SHORT,
    CONTENT_TOO_LONG,

    // PostId Validation
    INVALID_POST_ID_FORMAT,

    // Author Validation
    INVALID_AUTHOR,
    AUTHOR_NOT_FOUND,

    // Application Level
    CREATE_POST_FAILED,
    UPDATE_POST_FAILED,
    DELETE_POST_FAILED,
    PUBLISH_POST_FAILED,

    // Tag Validation
    BLANK_TAG,
    TAG_TOO_SHORT,
    TAG_TOO_LONG,
    TAG_CONTAINS_INVALID_CHAR,
    TOO_MANY_TAGS,
    DUPLICATE_TAG,

    // Version Validation
    INVALID_POST_VERSION_FORMAT,

    // Pagination Validation
    INVALID_PAGINATION_LIMIT,
    INVALID_PAGE_NUMBER,

    // Review
    INVALID_REVIEW_STATE,
    REVIEW_NOT_FOUND,
    REVIEW_ALREADY_EXISTS,
    REVIEW_EXPIRED,

    // Revision
    REVISION_NOT_FOUND,
    DUPLICATE_REVISION,

    // Vote
    ALREADY_VOTED,
    INVALID_VOTE,

    // Review Comment
    BLANK_REVIEW_COMMENT,
    REVIEW_COMMENT_TOO_LONG,
    INVALID_LINE_NUMBER,
    INVALID_REVIEW_COMMENT_ID_FORMAT,
    BLANK_SUGGESTED_CHANGE,
    SUGGESTED_CHANGE_TOO_LONG,
    TOTAL_SUGGESTED_CHANGES_TOO_LONG,

    // Generic
    VALIDATION_ERROR,
    DOMAIN_ERROR,
    INTERNAL_ERROR,
    INVALID_POST_REVIEW_ID_FORMAT,
}
