# Bulk Data Loader 전용 설정
# 대량 데이터 삽입 시 성능 최적화 설정

spring:
  # JPA 설정 - 대량 삽입 시 최적화
  jpa:
    show-sql: false  # SQL 로깅 비활성화 (성능 향상)
    properties:
      hibernate:
        jdbc:
          batch_size: 10000  # 배치 크기 증가
          batch_versioned_data: true
          fetch_size: 2000
        order_inserts: true
        order_updates: true
        generate_statistics: false  # 통계 비활성화
        cache:
          use_second_level_cache: false
          use_query_cache: false
  
  # 데이터소스 설정 - 커넥션 풀 확대
  datasource:
    hikari:
      maximum-pool-size: 50  # 병렬 처리를 위해 풀 크기 증가
      minimum-idle: 20
      connection-timeout: 60000  # 타임아웃 증가
      idle-timeout: 600000
      max-lifetime: 1800000
      connection-test-query: SELECT 1
      
  # Flyway 비활성화 (대량 삽입 시 불필요)
  flyway:
    enabled: false

# 로깅 설정 - 불필요한 로그 최소화
logging:
  level:
    org.springframework: WARN
    org.hibernate: WARN
    com.zaxxer.hikari: INFO
    me.helloc.techwikiplus.tools: INFO  # 벌크 로더만 INFO 레벨
    root: WARN
  pattern:
    console: "%d{HH:mm:ss.SSS} [%thread] %-5level %logger{36} - %msg%n"

# 메모리 관련 JVM 옵션 (실행 시 추가 권장)
# -Xms4g -Xmx8g -XX:+UseG1GC -XX:MaxGCPauseMillis=200