openapi: 3.0.1
info:
  title: TechWikiPlus API
  description: TechWikiPlus API Documentation
  version: LOCAL_VERSION
servers:
  - url: http://localhost:9000
    description: Local server
  - url: http://13.124.188.47:9000
    description: Production server
tags: []
paths: {}
components:
  schemas: {}
