groups:
  - name: techwikiplus-alerts
    rules:
      # 애플리케이션 다운 알림
      - alert: ApplicationDown
        expr: up{job="techwikiplus-app"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "TechWikiPlus 애플리케이션이 다운되었습니다"
          description: "{{ $labels.instance }}에서 1분 이상 애플리케이션이 응답하지 않습니다"

      # 높은 메모리 사용률
      - alert: HighMemoryUsage
        expr: (jvm_memory_used_bytes{area="heap"} / jvm_memory_max_bytes{area="heap"}) * 100 > 80
        for: 5m
        labels:
          severity: warning
        annotations:
          summary: "높은 메모리 사용률 감지"
          description: "JVM 힙 메모리 사용률이 {{ $value }}%입니다"

      # 높은 응답 시간
      - alert: HighResponseTime
        expr: histogram_quantile(0.95, rate(http_server_requests_seconds_bucket[5m])) > 2
        for: 3m
        labels:
          severity: warning
        annotations:
          summary: "높은 응답 시간 감지"
          description: "95퍼센타일 응답 시간이 {{ $value }}초입니다"

      # 높은 에러율
      - alert: HighErrorRate
        expr: rate(http_server_requests_total{status=~"5.."}[5m]) / rate(http_server_requests_total[5m]) * 100 > 5
        for: 3m
        labels:
          severity: critical
        annotations:
          summary: "높은 에러율 감지"
          description: "5xx 에러율이 {{ $value }}%입니다"

      # 데이터베이스 연결 실패
      - alert: DatabaseConnectionFailure
        expr: hikaricp_connections_active{pool="HikariPool-1"} == 0
        for: 1m
        labels:
          severity: critical
        annotations:
          summary: "데이터베이스 연결 실패"
          description: "활성 데이터베이스 연결이 없습니다"

  # Infrastructure alerts disabled - Redis/MySQL monitoring via exporter not configured
  # - name: infrastructure-alerts