global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  - "alert-rules.yml"

alerting:
  alertmanagers:
    - static_configs:
        - targets: []

scrape_configs:
  # Spring Boot 애플리케이션 메트릭 (프로덕션 환경)
  - job_name: 'techwikiplus-app'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['techwikiplus:9000']
    scrape_interval: 10s
    scrape_timeout: 5s

  # Prometheus 자체 메트릭
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Redis/MySQL/Node exporter jobs disabled - not configured
  # - job_name: 'redis'
  #   static_configs:
  #     - targets: ['redis_exporter:9121']
  #   scrape_interval: 30s
  #
  # - job_name: 'mysql'
  #   static_configs:
  #     - targets: ['mysql_exporter:9104']  
  #   scrape_interval: 30s
  #
  # - job_name: 'node'
  #   static_configs:
  #     - targets: ['node_exporter:9100']
  #   scrape_interval: 30s