package me.helloc.techwikiplus.user.domain.exception

enum class UserErrorCode {
    // User Status
    USER_DORMANT,
    USER_BANNED,
    USER_PENDING,
    USER_DELETED,

    // User Management
    DUPLICATE_EMAIL,
    DUPLICATE_NICKNAME,
    USER_NOT_FOUND,
    NO_STATUS_USER,
    NOT_FOUND_PENDING_USER,

    // Authentication
    INVALID_CREDENTIALS,
    PASSWORD_MISMATCH,
    UNAUTHORIZED,
    FORBIDDEN,

    // Token
    INVALID_TOKEN,
    TOKEN_EXPIRED,
    INVALID_TOKEN_TYPE,

    // Verification
    INVALID_VERIFICATION_CODE,
    REGISTRATION_EXPIRED,
    CODE_MISMATCH,

    // Notification
    NOTIFICATION_FAILED,

    // Application Level
    SIGNUP_FAILED,
    LOGIN_FAILED,
    VERIFICATION_FAILED,

    // Email Validation
    BLANK_EMAIL,
    INVALID_EMAIL_FORMAT,

    // Nickname Validation
    BLANK_NICKNAME,
    NICKNAME_TOO_SHORT,
    NICKNAME_TOO_LONG,
    NICKNAME_CONTAINS_SPACE,
    NICKNAME_CONTAINS_SPECIAL_CHAR,

    // Password Validation
    BLANK_PASSWORD,
    PASSWORD_TOO_SHORT,
    PASSWORD_TOO_LONG,
    PASSWORD_NO_UPPERCASE,
    PASSWORD_NO_LOWERCASE,
    PASSWORD_NO_SPECIAL_CHAR,

    // UserId Validation
    BLANK_USER_ID,
    USER_ID_TOO_LONG,
    INVALID_USER_ID_FORMAT,

    // Generic
    VALIDATION_ERROR,
    DOMAIN_ERROR,
    INTERNAL_ERROR,
}
